# PostgreSQL. Versions 9.3 and up are supported.
default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: <%= ENV["POSTGRES_HOST"] %>
  port: <%= ENV["POSTGRES_PORT"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: metrics_api_development

test:
  <<: *default
  database: metrics_api_test

production:
  <<: *default
  database: metrics_api_production
  username: metrics_api
  password: <%= ENV["METRICS_API_DATABASE_PASSWORD"] %>
