version: '3.7'
services:
  db:
    image: postgres:latest
    container_name: metrics_db
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: metrics_api_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  api:
    build:
      context: ./metrics_api
      dockerfile: Dockerfile
    container_name: metrics_api
    command: "./bin/rails server -p 3000 -b '0.0.0.0'"
    volumes:
      - ./metrics_api:/app
      - bundle:/bundle
    ports:
      - "3000:3000"
    env_file:
      - .env

    depends_on:
      - db

  client:
    build:
      context: ./metrics_client
      dockerfile: Dockerfile
    container_name: metrics_client
    command: sh -c "npm install && npm run dev"
    ports:
      - 5173:5173
    volumes:
      - ./metrics_client:/client
    depends_on:
      - api
networks:
  default:
    name: metrics

volumes:
  postgres_db:
  bundle:
