source 'https://rubygems.org'

ruby '3.1.4'

gem 'rails', '~> 7.1.3', '>= 7.1.3.2'

gem 'bootsnap', require: false
gem 'pg', '~> 1.1'
gem 'puma', '>= 5.0'
gem 'rack-cors'
gem 'tzinfo-data', platforms: %i[windows jruby]

group :development, :test do
  gem 'debug', platforms: %i[mri windows]
  gem 'faker'
  gem 'rspec-rails', '~> 6.1.0'
end

group :test do
  gem 'factory_bot_rails', '6.4.3'
  gem 'shoulda-matchers', '6.1.0'
end

group :development do
  gem 'error_highlight', '>= 0.4.0', platforms: [:ruby]
end
